### PR TITLE
Fix symbol creation on macOS.

### PR DESCRIPTION
**Pull request by jan-auer**
To start with, this pull request removes all CString allocations from
the code where borrowed CStr could be used. For some reason, this also
fixed a bug, where debug symbols from the dSYM file were not extracted
on macOS.

Furthermore, this pull request also adds a new `assert_snapshot_plain`
method, that allows nicer diffs of larger chunks of formatted text.
Since this breaks old snapshots, they are updated along the line, too.

### CODE REVIEW

**Comment by jan-auer** [comment]
The tests fail due to invalid fixture paths (tests/fixtures/Electron Framework.syms/electron.dmp on Linux and tests/fixtures/electron.dmpcode_ on macOS). I have been unable to reproduce the same error locally. 

Potentially we really cannot use a borrowed reference and must pass an owned CString to breakpad. I will investigate this tomorrow.

**Comment by mitsuhiko** [comment]
I wonder if it's just possible that the working directory is different on travis?

**Comment by jan-auer** [comment]
No, there's actually some garbage appended to the paths. It's especially clear with the macOS example: `tests/fixtures/electron.dmpcode_`. 

But also the other one should just be `tests/fixtures/Electron Framework.syms`. What's interesting is that there are different tests failing on Linux and macOS, but they are failing consistently in stable/beta/nightly and over multiple reruns.

**Comment by mitsuhiko** [comment]
That might just be because you make a `CStr` from a `&Path` or `&str` and they are not guaranteed to have a trailing null. You might need to actually make a copy there and force a null to be appended.

**Comment by jan-auer** [comment]
That's probably it. I will revert to `CString` tomorrow and make sure that the correct symbols are still generated.

**Comment by jan-auer** [comment]
Maybe, it's also possible to use [`CStr::from_bytes_with_nul`](https://doc.rust-lang.org/std/ffi/struct.CStr.html#method.from_bytes_with_nul). However that looks like it's supposed to return an error in the above case. I am wondering if there's a nice way to convert Paths to Strings without reallocating the underlying buffer.

**Comment by mitsuhiko** [comment]
That function will just crash most likely as you just overrun the buffer. What we do in other projects currently is to not use c strings at all but to pass out the length explicitly. However most likely that won't work with the breakpad library which expects null terminated strings :(

**Comment by jan-auer** [comment]
Alright, turns out that one has to be extra careful when passing strings over FFI as Rust aggressively  frees them as soon as possible. Thanks for your help, @mitsuhiko!

**Pull request merged**
