### PR TITLE
Cast SIGSTKSZ to int to fix build

### LINKED ISSUE #501: Build fails on gcc 11
**Description**

Someone is reporting a sentry compile error on gcc 11: https://github.com/MisterTea/EternalTerminal/issues/412

### PR DESCRIPTION
**Pull request by jubalh**
SIGSTKSZ is no longer a compile time constant in
glibc 2.34 and later.

Fix https://github.com/getsentry/sentry-native/issues/501

### CODE REVIEW

**Review by Swatinem — APPROVED** [review]
nice! can you rebase that on the `handler` branch please? that is the one we use in the client.

**Comment by jubalh** [comment]
Rebased and pushed. But seems this is confusing GitHub. Shall I open a new PR to `handler` instead of `master`?

**Comment by jubalh** [comment]
Please see https://github.com/getsentry/breakpad/pull/22 for a PR to `handler` instead of `master`.
You can choose which one to merge and we can close the other one :)

**Comment by Swatinem** [comment]
I merged #22

**Pull request closed without merging**
